function Ri = Reg1block(R,nr)

Ri = cell(1,nr);
for ii = 1:nr
    Ri{ii} = Reg1(...
    R.data.cdp_arg{1},... % kappa
    'offsets',R.data.offsets(ii:nr:end),...
    'beta',R.data.beta(ii:nr:end),...
    'type_penal','mex',...
    'nthread',jf('ncore'),...
    'distance_power',R.data.distance_power,...
    'mask',R.data.mask,...
    'pot_arg',R.data.pot_arg{1}...
    );
end
